/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/components/admin/junoAdminTheme.ts
 * Command: astryx theme build src/components/admin/junoAdminTheme.ts --out src/components/admin/junoAdminTheme.css
 * Generated: 2026-07-30T21:20:43.706Z
 */

/**
 * juno-admin theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { junoAdminTheme } from './juno-admin';
 *   import './juno-admin.css';
 */
export const junoAdminTheme = {
  name: 'juno-admin',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#e11d48, #fb7185)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #6A0032)",
    "--color-neutral": "light-dark(#22191C1A, #ECDFE333)",
    "--color-background-surface": "light-dark(#ffffff, #111111)",
    "--color-background-body": "light-dark(#f8fafc, #080808)",
    "--color-overlay": "light-dark(#22191C66, #22191C99)",
    "--color-overlay-hover": "light-dark(#22191C0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#22191C1A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#22191C0D, #22191C80)",
    "--color-text-primary": "light-dark(#171717, #ffffff)",
    "--color-text-secondary": "light-dark(#525252, #a3a3a3)",
    "--color-text-disabled": "light-dark(#9F8C91, #6B5A5E)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#000000, #FFFBFC)",
    "--color-icon-secondary": "light-dark(#3C2C31, #D6C1C7)",
    "--color-icon-disabled": "light-dark(#9F8C91, #6B5A5E)",
    "--color-background-card": "light-dark(#FFFBFC, #22191C)",
    "--color-background-popover": "light-dark(#FFFBFC, #382E30)",
    "--color-background-inverted": "light-dark(#22191C, #FFFBFC)",
    "--color-border": "light-dark(#22191C1A, #FBEDF11A)",
    "--color-border-emphasized": "light-dark(#BAA6AB, #534247)",
    "--color-skeleton": "light-dark(#BAA6AB, #534247)",
    "--color-track": "light-dark(#BAA6AB, #534247)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--radius-container": "16px"
  },

};
