/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/components/admin/junoAdminTheme.ts
 * Command: astryx theme build src/components/admin/junoAdminTheme.ts --out src/components/admin/junoAdminTheme.css
 * Generated: 2026-07-30T21:20:43.707Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const junoAdminTheme: DefinedTheme;
