import { StyleSheet } from "react-native";

// =============================================================================
// FILE: src/styles/appStyles.ts
// =============================================================================
export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000', // Pure black background
    padding: 4,
    paddingTop: 84,
  },
  header: {
    marginBottom: 32,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  formContainer: {
    backgroundColor: '#0F0F0F', // Very dark gray with subtle contrast
    borderRadius: 20,
    padding: 10,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#1A1A1A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 12,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 20,
    marginTop: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#2A2A2A',
    paddingBottom: 12,
    letterSpacing: 0.3,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    color: '#E0E0E0',
    marginBottom: 10,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  input: {
    backgroundColor: '#1A1A1A',
    color: '#F5F5F5',
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    fontWeight: '400',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  textArea: {
    minHeight: 120,
    textAlignVertical: 'top',
    paddingTop: 16,
    lineHeight: 22,
  },
  picker: {
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    gap: 12,
    paddingVertical: 4,
  },
  checkboxLabel: {
    color: '#F0F0F0',
    fontSize: 16,
    fontWeight: '500',
  },
  button: {
    backgroundColor: '#2A2A2A',
    paddingVertical: 18,
    paddingHorizontal: 32,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  addButton: {
    backgroundColor: '#1F1F1F',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#2F2F2F',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  removeBtn: {
    backgroundColor: '#3A1F1F',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#4A2A2A',
    shadowColor: '#DC3545',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  smallButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.2,
  },

    videoPickerContainer: {
    marginTop: 16,
    alignItems: 'center',
  },
  videoPreview: {
    width: 200,
    height: 120,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#2A2A2A',
    position: 'relative',
    backgroundColor: '#1A1A1A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0F0F0F',
  },
  videoLabel: {
    color: '#fff',
    fontSize: 12,
    marginTop: 8,
    fontWeight: '600',
  },
  videoRemoveButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(220, 53, 69, 0.9)',
    borderRadius: 18,
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  
  imagePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 16,
    gap: 12,
    justifyContent: 'flex-start',
  },
  imagePreview: {
    width: 145,
    height: 180,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#2A2A2A',
    position: 'relative',
    backgroundColor: '#1A1A1A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  imageThumbnail: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imageRemoveButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(220, 53, 69, 0.9)',
    borderRadius: 18,
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
});

export const componentStyles = StyleSheet.create({
  variantContainer: {
    backgroundColor: '#0F0F0F',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  variantTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#2A2A2A',
    paddingBottom: 8,
    letterSpacing: 0.2,
  },
  variantOptionTag: {
    backgroundColor: '#2A2A2A',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#3A3A3A',
  },
  variantOptionText: {
    color: '#F0F0F0',
    fontSize: 13,
    fontWeight: '500',
  },
  optionContainer: {
    backgroundColor: '#0F0F0F',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  attributeContainer: {
    backgroundColor: '#0F0F0F',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  sizeChartRow: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  sizeChartCellHeader: {
    backgroundColor: '#1F1F1F',
    padding: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    minWidth: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sizeChartInputHeader: {
    color: '#FFFFFF',
    fontWeight: '700',
    textAlign: 'center',
    width: '100%',
    paddingVertical: 6,
    letterSpacing: 0.2,
  },
  sizeChartCell: {
    backgroundColor: '#0A0A0A',
    padding: 12,
    borderWidth: 1,
    borderColor: '#1A1A1A',
    minWidth: 100,
    color: '#F0F0F0',
    textAlign: 'center',
    fontSize: 14,
  },
  card: {
    backgroundColor: '#0F0F0F',
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  tagChip: {
    backgroundColor: '#2A2A2A',
    borderRadius: 24,
    paddingVertical: 10,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  tagText: {
    color: '#F0F0F0',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.1,
  },
  closeButton: {
    marginLeft: 10,
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 16,
    opacity: 0.8,
  },
  pickerItem: {
    color: '#F0F0F0',
    backgroundColor: '#1A1A1A',
    fontSize: 16,
  },
  variantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    justifyContent: 'space-between',
    gap: 12,
  },
  variantInput: {
    flex: 1,
  },
  variantRemoveButton: {
    backgroundColor: '#4A2A2A',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#5A3A3A',
    shadowColor: '#DC3545',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  variantRemoveButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  // Additional enhanced styles
  focusedInput: {
    borderColor: '#4A4A4A',
    borderWidth: 2,
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 6,
  },
  disabledInput: {
    backgroundColor: '#0A0A0A',
    color: '#666666',
    borderColor: '#1A1A1A',
  },
  successButton: {
    backgroundColor: '#1F4A1F',
    borderColor: '#2F5A2F',
  },
  warningButton: {
    backgroundColor: '#4A3A1F',
    borderColor: '#5A4A2F',
  },
  primaryAccent: {
    backgroundColor: '#2A4A7A',
    borderColor: '#3A5A8A',
  },
  secondaryAccent: {
    backgroundColor: '#4A2A7A',
    borderColor: '#5A3A8A',
  },
});